name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add remote
        env:
          HF: ${{ secrets.HF }}
        run: git remote add space https://MahnoorDS:${{ secrets.HF }}@huggingface.co/spaces/MahnoorDS/mlops-deployment-new

      - name: Push to hub
        env:
          HF: ${{ secrets.HF }}
        run: git push --force https://MahnoorDS:${{ secrets.HF }}@huggingface.co/spaces/MahnoorDS/mlops-deployment-new main
