name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Step 2: Add remote
      - name: Add remote
        env:
          HF: ${{ secrets.HF_TOKEN }}
        run: git remote add space https://MahnoorDS:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/MahnoorDS/mlops-deployment-new

      # Step 3: Push to Hugging Face Space
      - name: Push to hub
        env:
          HF: ${{ secrets.HF_TOKEN }}
        run: git push --force https://MahnoorDS:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/MahnoorDS/mlops-deployment-new main
