name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Step 4: Clone the Hugging Face Space (using Git)
    - name: Clone Hugging Face Space
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        git clone https://huggingface.co/spaces/MahnoorDS/mlops-deployment-new
        cd mlops-deployment-new
        git config --global user.email "your-email@example.com"
        git config --global user.name "Your Name"
    
    # Step 5: Copy Files to Space (exclude the Space directory itself)
    - name: Copy Files to Space
      run: |
        cp -r ./* mlops-deployment-new/  # Copy everything except the mlops-deployment-new directory itself
        cd mlops-deployment-new

    # Step 6: Push changes to the Hugging Face Space
    - name: Push to Hugging Face Space
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
      run: |
        cd mlops-deployment-new
        git add .
        git commit -m "Deploy to Hugging Face Space"
        git push https://$HF_TOKEN@huggingface.co/spaces/MahnoorDS/mlops-deployment-new
